window.TOOLS = [
  {
    "name": "ImportExcel",
    "slug": "importexcel",
    "category": "automation system",
    "status": "live",
    "repo": "dfinke/ImportExcel",
    "stars": 2734,
    "forks": 415,
    "language": "PowerShell",
    "updated": "2026-08-22",
    "oneLiner": "Import and export Excel spreadsheets from PowerShell without requiring Excel.",
    "description": "ImportExcel automates spreadsheet creation, reading, reporting, tables, charts, and pivot tables from PowerShell across Windows, Linux, and macOS.",
    "image": "https://github.com/dfinke/ImportExcel/raw/refs/heads/master/images/SalesDataChart.png",
    "imageAlt": "A generated Excel chart created by ImportExcel",
    "githubUrl": "https://github.com/dfinke/ImportExcel",
    "zipUrl": "https://github.com/dfinke/ImportExcel/archive/refs/heads/master.zip",
    "youtubeUrl": "",
    "demoUrl": null,
    "packageUrl": "https://www.powershellgallery.com/packages/ImportExcel",
    "articleUrl": "https://github.com/dfinke/ImportExcel/tree/master/Examples",
    "installCommand": "Install-Module -Name ImportExcel",
    "tags": [
      "PowerShell",
      "Excel automation",
      "reports",
      "developer tooling",
      "automation"
    ],
    "featured": true
  },
  {
    "name": "PSAI",
    "slug": "psai",
    "category": "AI agent framework",
    "status": "live",
    "repo": "dfinke/PSAI",
    "stars": 269,
    "forks": 35,
    "language": "PowerShell",
    "updated": "2026-03-22",
    "oneLiner": "PowerShell-native AI agents and multi-agent orchestration.",
    "description": "PSAI is a framework for building high-agency AI tools and autonomous agents inside PowerShell workflows, including tool use, orchestration, and provider integration.",
    "image": "https://github.com/dfinke/PSAI/raw/refs/heads/main/Media/PSAI.png",
    "imageAlt": "PSAI project mark",
    "githubUrl": "https://github.com/dfinke/PSAI",
    "zipUrl": "https://github.com/dfinke/PSAI/archive/refs/heads/main.zip",
    "youtubeUrl": "",
    "demoUrl": null,
    "packageUrl": "https://www.powershellgallery.com/packages/PSAI",
    "articleUrl": "https://github.com/dfinke/PSAI/wiki",
    "installCommand": "Install-Module -Name PSAI",
    "tags": [
      "AI agents",
      "PowerShell",
      "LLMs",
      "OpenAI",
      "automation",
      "developer tooling"
    ],
    "featured": true
  },
  {
    "name": "PSAISuite",
    "slug": "psaisuite",
    "category": "AI provider abstraction",
    "status": "live",
    "repo": "dfinke/psaisuite",
    "stars": 90,
    "forks": 16,
    "language": "PowerShell",
    "updated": "2026-09-01",
    "oneLiner": "A provider-agnostic PowerShell interface for 15+ GenAI providers.",
    "description": "PSAISuite standardizes access to multiple LLM providers from PowerShell, supporting provider switching, benchmarking, tool-calling workflows, and high-performance AI integration.",
    "image": "https://github.com/dfinke/PSAISuite/raw/refs/heads/main/assets/InvokeChatCompletion.png",
    "imageAlt": "PSAISuite command output",
    "githubUrl": "https://github.com/dfinke/psaisuite",
    "zipUrl": "https://github.com/dfinke/psaisuite/archive/refs/heads/main.zip",
    "youtubeUrl": "",
    "demoUrl": null,
    "packageUrl": "https://www.powershellgallery.com/packages/PSAISuite",
    "articleUrl": "https://github.com/dfinke/psaisuite/tree/main/guides",
    "installCommand": "Install-Module PSAISuite",
    "tags": [
      "LLMs",
      "AI agents",
      "OpenAI",
      "Claude",
      "PowerShell",
      "benchmarking",
      "developer tooling"
    ],
    "featured": true
  },
  {
    "name": "PSClaudeCode",
    "slug": "psclaudecode",
    "category": "agent workflow experiment",
    "status": "prototype",
    "repo": "dfinke/PSClaudeCode",
    "stars": 83,
    "forks": 14,
    "language": "PowerShell",
    "updated": "2026-06-03",
    "oneLiner": "A PowerShell implementation of a Claude Code-style agent loop.",
    "description": "PSClaudeCode explores how a Claude-powered coding agent can work from PowerShell, including iterative task execution, tool use, file operations, permission checks, and conversational workflows.",
    "image": "https://img.youtube.com/vi/7choAjuJ2BA/maxresdefault.jpg",
    "imageAlt": "Claude Code built natively in PowerShell video thumbnail",
    "githubUrl": "https://github.com/dfinke/PSClaudeCode",
    "zipUrl": "https://github.com/dfinke/PSClaudeCode/archive/refs/heads/main.zip",
    "youtubeUrl": "https://www.youtube.com/watch?v=7choAjuJ2BA",
    "demoUrl": "https://www.youtube.com/watch?v=7choAjuJ2BA",
    "packageUrl": null,
    "articleUrl": "",
    "installCommand": "Import-Module .\\PSClaudeCode.psd1",
    "tags": [
      "Claude",
      "AI agents",
      "developer tooling",
      "PowerShell",
      "automation",
      "agent workflows"
    ],
    "featured": true
  },
  {
    "name": "PSUnplugged",
    "slug": "psunplugged",
    "category": "Codex automation shell",
    "status": "read-only release",
    "repo": "dfinke/PSUnplugged",
    "stars": 18,
    "forks": 5,
    "language": "PowerShell",
    "updated": "2026-06-02",
    "oneLiner": "A PowerShell orchestration shell for the OpenAI Codex App Server.",
    "description": "PSUnplugged gives PowerShell users a terminal-native way to drive the Codex runtime while inheriting conversation history, approvals, streamed agent events, MCP servers, skills, and plugins.",
    "image": "https://github.com/dfinke/PSUnplugged/raw/refs/heads/main/media/PSUnplugged.png",
    "imageAlt": "PSUnplugged project graphic",
    "githubUrl": "https://github.com/dfinke/PSUnplugged",
    "zipUrl": "https://github.com/dfinke/PSUnplugged/archive/refs/heads/main.zip",
    "youtubeUrl": "",
    "demoUrl": null,
    "packageUrl": null,
    "articleUrl": "https://forms.gle/gvw8cU2pgFeXWMNZA",
    "installCommand": "git clone https://github.com/dfinke/PSUnplugged",
    "tags": [
      "Codex",
      "OpenAI",
      "MCP",
      "AI agents",
      "PowerShell",
      "developer tooling",
      "automation"
    ],
    "featured": true
  },
  {
    "name": "PSPandas",
    "slug": "pspandas",
    "category": "CLI",
    "status": "Live",
    "repo": "dfinke/PSPandas",
    "stars": 0,
    "forks": 0,
    "language": "PowerShell",
    "updated": "2026-08-28",
    "oneLiner": "PowerShell-native data frames for filtering, grouping, joining, and analyzing objects.",
    "description": "PowerShell-native data frames for filtering, grouping, joining, and analyzing objects.",
    "image": "assets/project-placeholder.svg",
    "imageAlt": "PSPandas project graphic",
    "githubUrl": "https://github.com/dfinke/PSPandas",
    "zipUrl": "https://github.com/dfinke/PSPandas/archive/refs/heads/main.zip",
    "youtubeUrl": "",
    "demoUrl": null,
    "packageUrl": null,
    "articleUrl": "",
    "installCommand": "",
    "tags": [],
    "featured": false
  }
];

window.SOCIAL_LINKS = [
  {
    "label": "Join the Forge",
    "url": "https://www.skool.com/agentic-ai-forge",
    "icon": "flame",
    "text": "Join the Agentic AI Forge community."
  },
  {
    "label": "X / Twitter",
    "url": "https://x.com/dfinke",
    "icon": "x-twitter",
    "text": "Short updates and build notes."
  },
  {
    "label": "YouTube",
    "url": "https://youtube.com/@dougfinke/",
    "icon": "youtube",
    "text": "Walkthroughs, demos, and talks."
  },
  {
    "label": "New York - Agentic AI",
    "url": "https://www.meetup.com/nycpowershellmeetup/",
    "icon": "users-round",
    "text": "Meetup sessions and community events."
  },
  {
    "label": "GitHub",
    "url": "https://github.com/dfinke",
    "icon": "github",
    "text": "Source code, issues, and new experiments."
  },
  {
    "label": "LinkedIn",
    "url": "https://www.linkedin.com/in/douglasfinke",
    "icon": "linkedin",
    "text": "Professional background and connections."
  },
  {
    "label": "Intent-First AI by Example",
    "url": "https://dougfinke.gumroad.com/l/rjtij",
    "icon": "shopping-bag",
    "text": "A practical AI resource on Gumroad."
  },
  {
    "label": "Sessionize",
    "url": "https://sessionize.com/douglas-finke/",
    "icon": "mic",
    "text": "Speaker profile, talks, and sessions."
  }
];